version: '3.7'

services:
  app:
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env
    depends_on:
      - mysql
    environment:
      - DB_HOST=host.docker.internal
  mysql:
    image: mysql:latest
    ports:
      - 8083:${DB_PORT}
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - .env