name: latest changes

on:
  pull_request_target:
    branches:
      - develop
    types:
      - closed
  # For manually triggering it
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://tiangolo/latest-changes:0.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          latest_changes_file: out/changelog.md
          latest_changes_header: '## Latest Changes\n\n'
          debug_logs: true
